/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esports.view;

/**
 *
 * @author raz3d
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public void reset() {
    tfUsername.setText("");
    pfPassword.setText("");
    lblStatus.setText(" ");
    tfUsername.requestFocus();
}
    public LoginPanel(MainFrame aThis) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCard = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblUsernameHeader = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lblPasswordHeader = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 11, 19));

        pnlCard.setBackground(new java.awt.Color(20, 25, 44));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(99, 102, 241));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("⚔  NEXUS CUP");

        lblSubtitle.setForeground(new java.awt.Color(71, 85, 105));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("Esports Management System");

        lblUsernameHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblUsernameHeader.setForeground(new java.awt.Color(148, 163, 184));
        lblUsernameHeader.setText("Username");

        tfUsername.setBackground(new java.awt.Color(12, 16, 28));
        tfUsername.setForeground(new java.awt.Color(241, 245, 249));

        lblPasswordHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPasswordHeader.setForeground(new java.awt.Color(148, 163, 184));
        lblPasswordHeader.setText("Password");

        pfPassword.setBackground(new java.awt.Color(12, 16, 28));
        pfPassword.setForeground(new java.awt.Color(241, 245, 249));
        pfPassword.addActionListener(this::pfPasswordActionPerformed);

        btnLogin.setBackground(new java.awt.Color(99, 102, 241));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(241, 245, 249));
        btnLogin.setText("Sign In");
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblStatus.setForeground(new java.awt.Color(239, 68, 68));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsernameHeader)
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblPasswordHeader))))
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblTitle))
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblSubtitle))
                    .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCardLayout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pfPassword)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCardLayout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(btnLogin))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(193, 193, 193))
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(24, 24, 24)
                .addComponent(lblUsernameHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPasswordHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String user = tfUsername.getText().trim();
    String pass = new String(pfPassword.getPassword());
    esports.controller.AuthController auth = new esports.controller.AuthController();
    if (auth.login(user, pass)) {
        esports.model.Session s = esports.model.Session.getInstance();
        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.resetDashboards();
        if ("ADMIN".equals(s.getCurrentUser().getRole())) frame.showAdminDashboard();
        else frame.showManagerDashboard();
    } else {
        lblStatus.setText("Invalid username or password.");
        lblStatus.setForeground(new java.awt.Color(239, 68, 68));
        pfPassword.setText("");
    }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPasswordHeader;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsernameHeader;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
