/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esports.view.admin;

/**
 *
 * @author raz3d
 */
public class ChangePasswordPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChangePasswordPanel
     */
    public ChangePasswordPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnChange = new javax.swing.JButton();
        pfNew = new javax.swing.JPasswordField();
        lblNew = new javax.swing.JLabel();
        pfCurrent = new javax.swing.JPasswordField();
        lblCurrent = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        pfConfirm = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 11, 19));

        jPanel1.setBackground(new java.awt.Color(20, 25, 44));

        btnChange.setBackground(new java.awt.Color(99, 102, 241));
        btnChange.setForeground(new java.awt.Color(255, 255, 255));
        btnChange.setText("Update Password");
        btnChange.setBorderPainted(false);
        btnChange.setFocusPainted(false);
        btnChange.addActionListener(this::btnChangeActionPerformed);

        pfNew.setBackground(new java.awt.Color(12, 16, 28));
        pfNew.setForeground(new java.awt.Color(255, 255, 255));

        lblNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNew.setForeground(new java.awt.Color(148, 163, 184));
        lblNew.setText("New Password");

        pfCurrent.setBackground(new java.awt.Color(12, 16, 28));
        pfCurrent.setForeground(new java.awt.Color(255, 255, 255));

        lblCurrent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurrent.setForeground(new java.awt.Color(148, 163, 184));
        lblCurrent.setText("Current Password");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(241, 245, 249));
        lblTitle.setText("Change Password");

        lblConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfirm.setForeground(new java.awt.Color(148, 163, 184));
        lblConfirm.setText("Confirm New Password");

        pfConfirm.setBackground(new java.awt.Color(12, 16, 28));
        pfConfirm.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNew)
                            .addComponent(pfCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfNew, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCurrent)
                            .addComponent(lblTitle)
                            .addComponent(lblConfirm)
                            .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblStatus)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addComponent(lblCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNew)
                .addGap(18, 18, 18)
                .addComponent(pfNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfirm)
                .addGap(18, 18, 18)
                .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(lblStatus)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
       String current = new String(pfCurrent.getPassword());
    String newPass = new String(pfNew.getPassword()).trim();
    String confirm = new String(pfConfirm.getPassword()).trim();

    if (newPass.isEmpty()) {
        setStatus("New password cannot be empty.", false); return;
    }
    if (newPass.length() < 6) {
        setStatus("Password must be at least 6 characters.", false); return;
    }
    if (!newPass.equals(confirm)) {
        setStatus("New passwords do not match.", false); return;
    }

    esports.controller.AdminController ctrl =
        new esports.controller.AdminController();
    String err = ctrl.changeOwnPassword(current, newPass);

    if (err == null) {
        setStatus("Password changed successfully!", true);
        pfCurrent.setText("");
        pfNew.setText("");
        pfConfirm.setText("");
    } else {
        setStatus(err, false);
    }
    }//GEN-LAST:event_btnChangeActionPerformed
private void setStatus(String msg, boolean success) {
    lblStatus.setText(msg);
    lblStatus.setForeground(success
        ? new java.awt.Color(16, 185, 129)
        : new java.awt.Color(239, 68, 68));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField pfConfirm;
    private javax.swing.JPasswordField pfCurrent;
    private javax.swing.JPasswordField pfNew;
    // End of variables declaration//GEN-END:variables
}
