/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esports.view.admin;

/**
 *
 * @author raz3d
 */
public class RegisterManagerPanel extends javax.swing.JPanel {
public void refresh() {
    esports.controller.AdminController ctrl = new esports.controller.AdminController();
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblManagers.getModel();
    model.setRowCount(0);
    for (esports.model.Manager m : ctrl.getManagers()) {
        esports.model.Team t = ctrl.getTeamById(m.hasTeam() ? m.getTeamId() : "");
        model.addRow(new Object[]{
            m.getFullName(), m.getUsername(),
            t != null ? t.getName() : "— No team"
        });
    }
}
    /**
     * Creates new form RegisterManagerPanel
     */
    public RegisterManagerPanel(AdminDashboard aThis) {
        initComponents();
        tblManagers.getTableHeader().setBackground(new java.awt.Color(14, 18, 30));
tblManagers.getTableHeader().setForeground(new java.awt.Color(148, 163, 184));
tblManagers.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
tblManagers.setSelectionBackground(new java.awt.Color(99, 102, 241, 60));
scrollManagers.getViewport().setBackground(new java.awt.Color(20, 26, 44));
refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        tfFullName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        lblFormStatus = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        scrollManagers = new javax.swing.JScrollPane();
        tblManagers = new javax.swing.JTable();
        btnRemoveManager = new javax.swing.JButton();

        setBackground(new java.awt.Color(9, 11, 19));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 245, 249));
        jLabel1.setText("Manager Registration");

        pnlForm.setBackground(new java.awt.Color(20, 25, 44));

        lblFormTitle.setBackground(new java.awt.Color(148, 163, 184));
        lblFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblFormTitle.setText("Create Manager Account");

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(148, 163, 184));
        lblFullName.setText("Full Name");

        tfFullName.setBackground(new java.awt.Color(12, 16, 28));
        tfFullName.setForeground(new java.awt.Color(241, 245, 249));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(148, 163, 184));
        lblUsername.setText("Username");

        tfUsername.setBackground(new java.awt.Color(12, 16, 28));
        tfUsername.setForeground(new java.awt.Color(241, 245, 249));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(148, 163, 184));
        lblPassword.setText("Password");

        pfPassword.setBackground(new java.awt.Color(12, 16, 28));
        pfPassword.setForeground(new java.awt.Color(241, 245, 249));

        btnRegister.setBackground(new java.awt.Color(99, 102, 241));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(241, 245, 249));
        btnRegister.setText("Register Manager");
        btnRegister.setBorderPainted(false);
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        lblFormStatus.setBackground(new java.awt.Color(12, 16, 28));
        lblFormStatus.setForeground(new java.awt.Color(148, 163, 184));

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormTitle)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister))))
                .addGap(110, 110, 110))
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblFullName))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblFormStatus))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblUsername))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblPassword)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblFormTitle)
                .addGap(18, 18, 18)
                .addComponent(lblFullName)
                .addGap(18, 18, 18)
                .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormStatus))
        );

        pnlTable.setBackground(new java.awt.Color(20, 25, 44));

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblTableTitle.setText("Registered Managers");

        tblManagers.setBackground(new java.awt.Color(20, 25, 44));
        tblManagers.setForeground(new java.awt.Color(241, 245, 249));
        tblManagers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full Name", "Username", "Team"
            }
        ));
        tblManagers.setFocusable(false);
        tblManagers.setGridColor(new java.awt.Color(30, 38, 60));
        tblManagers.setRowHeight(38);
        tblManagers.setShowGrid(false);
        scrollManagers.setViewportView(tblManagers);

        btnRemoveManager.setBackground(new java.awt.Color(239, 68, 68));
        btnRemoveManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemoveManager.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveManager.setText("Remove Selected");
        btnRemoveManager.setBorderPainted(false);
        btnRemoveManager.addActionListener(this::btnRemoveManagerActionPerformed);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemoveManager)
                .addGap(90, 90, 90))
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(scrollManagers, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblTableTitle)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTableTitle)
                .addGap(18, 18, 18)
                .addComponent(scrollManagers, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveManager)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
       esports.controller.AdminController ctrl = new esports.controller.AdminController();
    String err = ctrl.registerManager(
        tfUsername.getText(), new String(pfPassword.getPassword()), tfFullName.getText());
    if (err == null) {
        lblFormStatus.setForeground(new java.awt.Color(16, 185, 129));
        lblFormStatus.setText("Manager registered successfully.");
        tfUsername.setText(""); pfPassword.setText(""); tfFullName.setText("");
        refresh();
    } else {
        lblFormStatus.setForeground(new java.awt.Color(239, 68, 68));
        lblFormStatus.setText(err);
    }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRemoveManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveManagerActionPerformed
         int row = tblManagers.getSelectedRow();
    if (row < 0) { return; }
    String username = (String) tblManagers.getModel().getValueAt(row, 1);
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Remove manager '" + username + "' and their team?",
        "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        esports.controller.AdminController ctrl = new esports.controller.AdminController();
        ctrl.removeManager(username);
        refresh();
    }
    }//GEN-LAST:event_btnRemoveManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRemoveManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFormStatus;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JScrollPane scrollManagers;
    private javax.swing.JTable tblManagers;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
