/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esports.view.admin;

/**
 *
 * @author raz3d
 */
public class RegisterManagerPanel extends javax.swing.JPanel {
public void refresh() {
    esports.controller.AdminController ctrl = new esports.controller.AdminController();
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblManagers.getModel();
    model.setRowCount(0);
    for (esports.model.Manager m : ctrl.getManagers()) {
        esports.model.Team t = ctrl.getTeamById(m.hasTeam() ? m.getTeamId() : "");
        model.addRow(new Object[]{
            m.getFullName(), m.getUsername(),
            t != null ? t.getName() : "— No team"
        });
    }
}
    /**
     * Creates new form RegisterManagerPanel
     */
    public RegisterManagerPanel(AdminDashboard aThis) {
        initComponents();
        tblManagers.getTableHeader().setBackground(new java.awt.Color(14, 18, 30));
tblManagers.getTableHeader().setForeground(new java.awt.Color(148, 163, 184));
tblManagers.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
tblManagers.setSelectionBackground(new java.awt.Color(99, 102, 241, 60));
scrollManagers.getViewport().setBackground(new java.awt.Color(20, 26, 44));
refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        tfFullName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        lblFormStatus = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        scrollManagers = new javax.swing.JScrollPane();
        tblManagers = new javax.swing.JTable();
        btnRemoveManager = new javax.swing.JButton();
        btnResetPassword = new javax.swing.JButton();

        setBackground(new java.awt.Color(9, 11, 19));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 245, 249));
        jLabel1.setText("Manager Registration");

        pnlForm.setBackground(new java.awt.Color(20, 25, 44));

        lblFormTitle.setBackground(new java.awt.Color(148, 163, 184));
        lblFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblFormTitle.setText("Create Manager Account");

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(148, 163, 184));
        lblFullName.setText("Full Name");

        tfFullName.setBackground(new java.awt.Color(12, 16, 28));
        tfFullName.setForeground(new java.awt.Color(241, 245, 249));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(148, 163, 184));
        lblUsername.setText("Username");

        tfUsername.setBackground(new java.awt.Color(12, 16, 28));
        tfUsername.setForeground(new java.awt.Color(241, 245, 249));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(148, 163, 184));
        lblPassword.setText("Password");

        pfPassword.setBackground(new java.awt.Color(12, 16, 28));
        pfPassword.setForeground(new java.awt.Color(241, 245, 249));

        btnRegister.setBackground(new java.awt.Color(99, 102, 241));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(241, 245, 249));
        btnRegister.setText("Register Manager");
        btnRegister.setBorderPainted(false);
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        lblFormStatus.setBackground(new java.awt.Color(12, 16, 28));
        lblFormStatus.setForeground(new java.awt.Color(148, 163, 184));

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblFormStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(lblUsername)
                    .addComponent(lblFullName))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormTitle)
                    .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                            .addComponent(btnRegister)
                            .addGap(117, 117, 117))
                        .addGroup(pnlFormLayout.createSequentialGroup()
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblFormTitle)
                .addGap(18, 18, 18)
                .addComponent(lblFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addGap(12, 12, 12)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblFormStatus))
        );

        pnlTable.setBackground(new java.awt.Color(20, 25, 44));

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblTableTitle.setText("Registered Managers");

        scrollManagers.setBackground(new java.awt.Color(0, 0, 0));

        tblManagers.setBackground(new java.awt.Color(20, 25, 44));
        tblManagers.setForeground(new java.awt.Color(255, 255, 255));
        tblManagers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full Name", "Username", "Team"
            }
        ));
        tblManagers.setFocusable(false);
        tblManagers.setGridColor(new java.awt.Color(30, 38, 60));
        tblManagers.setRowHeight(38);
        tblManagers.setShowGrid(false);
        scrollManagers.setViewportView(tblManagers);

        btnRemoveManager.setBackground(new java.awt.Color(239, 68, 68));
        btnRemoveManager.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemoveManager.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveManager.setText("Remove Selected");
        btnRemoveManager.setBorderPainted(false);
        btnRemoveManager.addActionListener(this::btnRemoveManagerActionPerformed);

        btnResetPassword.setBackground(new java.awt.Color(245, 158, 11));
        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPassword.setText("Reset Password");
        btnResetPassword.setBorderPainted(false);
        btnResetPassword.setFocusPainted(false);
        btnResetPassword.addActionListener(this::btnResetPasswordActionPerformed);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblTableTitle)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(pnlTableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollManagers, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnRemoveManager)
                .addGap(30, 30, 30)
                .addComponent(btnResetPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollManagers, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveManager)
                    .addComponent(btnResetPassword))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
       esports.controller.AdminController ctrl = new esports.controller.AdminController();
    String err = ctrl.registerManager(
        tfUsername.getText(), new String(pfPassword.getPassword()), tfFullName.getText());
    if (err == null) {
        lblFormStatus.setForeground(new java.awt.Color(16, 185, 129));
        lblFormStatus.setText("Manager registered successfully.");
        tfUsername.setText(""); pfPassword.setText(""); tfFullName.setText("");
        refresh();
    } else {
        lblFormStatus.setForeground(new java.awt.Color(239, 68, 68));
        lblFormStatus.setText(err);
    }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRemoveManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveManagerActionPerformed
         int row = tblManagers.getSelectedRow();
    if (row < 0) { return; }
    String username = (String) tblManagers.getModel().getValueAt(row, 1);
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Remove manager '" + username + "' and their team?",
        "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        esports.controller.AdminController ctrl = new esports.controller.AdminController();
        ctrl.removeManager(username);
        refresh();
    }
    }//GEN-LAST:event_btnRemoveManagerActionPerformed

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
         int row = tblManagers.getSelectedRow();
    if (row < 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please select a manager first.",
            "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String fullName = (String) tblManagers.getModel().getValueAt(row, 0);
String username = (String) tblManagers.getModel().getValueAt(row, 1);

    // Ask admin for new password
    javax.swing.JPasswordField pf = new javax.swing.JPasswordField();
    pf.setPreferredSize(new java.awt.Dimension(200, 36));

    int result = javax.swing.JOptionPane.showConfirmDialog(
        this,
        new Object[]{
            "Reset password for: " + fullName,
            "Enter new password:", pf
        },
        "Reset Password",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (result != javax.swing.JOptionPane.OK_OPTION) return;

    String newPass = new String(pf.getPassword()).trim();
    esports.controller.AdminController ctrl =
        new esports.controller.AdminController();
    String err = ctrl.resetManagerPassword(username, newPass);

    if (err == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Password reset successfully for " + fullName + ".\n" +
            "They can now log in with the new password.",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + err, "Failed",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnResetPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRemoveManager;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFormStatus;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JScrollPane scrollManagers;
    private javax.swing.JTable tblManagers;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
