/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esports.view.admin;

/**
 *
 * @author raz3d
 */
public class TeamsPanel extends javax.swing.JPanel {
private void loadRoster() {
    int row = tblTeams.getSelectedRow();
    javax.swing.table.DefaultTableModel pm =
        (javax.swing.table.DefaultTableModel) tblPlayers.getModel();
    pm.setRowCount(0);
    if (row < 0) return;
    String teamName = (String) tblTeams.getModel().getValueAt(row, 0);
    esports.controller.AdminController ctrl = new esports.controller.AdminController();
    for (esports.model.Team t : ctrl.getTeams()) {
        if (t.getName().equals(teamName)) {
            lblRosterTitle.setText("ROSTER: " + t.getName().toUpperCase());
            int n = 1;
            for (esports.model.Player p : t.getPlayers()) {
                String role = "Sixth Man".equals(p.getRole()) ? "⭐ " + p.getRole() : p.getRole();
                pm.addRow(new Object[]{n++, p.getName(), p.getIgn(), role});
            }
        }
    }
}

public void refresh() {
    esports.controller.AdminController ctrl = new esports.controller.AdminController();
    javax.swing.table.DefaultTableModel tm =
        (javax.swing.table.DefaultTableModel) tblTeams.getModel();
    tm.setRowCount(0);
    for (esports.model.Team t : ctrl.getTeams()) {
        String mName = ctrl.getManagers().stream()
            .filter(m -> t.getId().equals(m.getTeamId()))
            .map(m -> m.getFullName()).findFirst().orElse("—");
        tm.addRow(new Object[]{t.getName(), mName, t.getPlayerCount() + "/6"});
    }
    ((javax.swing.table.DefaultTableModel) tblPlayers.getModel()).setRowCount(0);
    lblRosterTitle.setText("SELECT A TEAM TO VIEW ROSTER");
}
    /**
     * Creates new form TeamsPanel
     */
    public TeamsPanel() {
        initComponents();
        for (javax.swing.JTable t : new javax.swing.JTable[]{tblTeams, tblPlayers}) {
    t.getTableHeader().setBackground(new java.awt.Color(14, 18, 30));
    t.getTableHeader().setForeground(new java.awt.Color(148, 163, 184));
    t.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
    t.setSelectionBackground(new java.awt.Color(99, 102, 241, 60));
}
scrollTeams.getViewport().setBackground(new java.awt.Color(20, 26, 44));
scrollPlayers.getViewport().setBackground(new java.awt.Color(20, 26, 44));

// When a team row is clicked, load its roster
tblTeams.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting()) loadRoster();
});
refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageTitle = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        lblTeamsTitle = new javax.swing.JLabel();
        scrollTeams = new javax.swing.JScrollPane();
        tblTeams = new javax.swing.JTable();
        pnlRight = new javax.swing.JPanel();
        lblRosterTitle = new javax.swing.JLabel();
        scrollPlayers = new javax.swing.JScrollPane();
        tblPlayers = new javax.swing.JTable();

        setBackground(new java.awt.Color(9, 11, 19));

        lblPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPageTitle.setText("All Teams");

        pnlLeft.setBackground(new java.awt.Color(20, 25, 44));

        lblTeamsTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTeamsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTeamsTitle.setText("REGISTERED TEAMS");

        tblTeams.setBackground(new java.awt.Color(20, 25, 44));
        tblTeams.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblTeams.setForeground(new java.awt.Color(255, 255, 255));
        tblTeams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Team Name", "Manager", "Players"
            }
        ));
        tblTeams.setFocusable(false);
        tblTeams.setGridColor(new java.awt.Color(30, 38, 60));
        tblTeams.setRowHeight(38);
        scrollTeams.setViewportView(tblTeams);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scrollTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTeamsTitle))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTeamsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlRight.setBackground(new java.awt.Color(20, 25, 44));

        lblRosterTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRosterTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRosterTitle.setText("SELECT A TEAM TO VIEW ROSTER");

        scrollPlayers.setBackground(new java.awt.Color(20, 25, 44));
        scrollPlayers.setForeground(new java.awt.Color(255, 255, 255));

        tblPlayers.setBackground(new java.awt.Color(20, 25, 44));
        tblPlayers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblPlayers.setForeground(new java.awt.Color(255, 255, 255));
        tblPlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Player Name", "IGN", "Role"
            }
        ));
        tblPlayers.setFocusable(false);
        tblPlayers.setGridColor(new java.awt.Color(30, 38, 60));
        tblPlayers.setRowHeight(38);
        scrollPlayers.setViewportView(tblPlayers);

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRosterTitle)
                    .addComponent(scrollPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblRosterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPageTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblPageTitle)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblRosterTitle;
    private javax.swing.JLabel lblTeamsTitle;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JScrollPane scrollPlayers;
    private javax.swing.JScrollPane scrollTeams;
    private javax.swing.JTable tblPlayers;
    private javax.swing.JTable tblTeams;
    // End of variables declaration//GEN-END:variables
}
