/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esports.view.manager;

/**
 *
 * @author raz3d
 */
public class ChangePasswordPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChangePasswordPanel
     */
    public ChangePasswordPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCurrent = new javax.swing.JLabel();
        pfCurrent = new javax.swing.JPasswordField();
        lblNew = new javax.swing.JLabel();
        pfNew = new javax.swing.JPasswordField();
        lblConfirm = new javax.swing.JLabel();
        pfConfirm = new javax.swing.JPasswordField();
        btnChange = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 11, 19));

        jPanel1.setBackground(new java.awt.Color(20, 25, 44));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(148, 163, 184));
        lblTitle.setText("Change Password");

        lblCurrent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurrent.setForeground(new java.awt.Color(148, 163, 184));
        lblCurrent.setText("Current Password");

        pfCurrent.setBackground(new java.awt.Color(12, 16, 28));
        pfCurrent.setText("jPasswordField1");

        lblNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNew.setForeground(new java.awt.Color(148, 163, 184));
        lblNew.setText("New Password");

        pfNew.setBackground(new java.awt.Color(12, 16, 28));
        pfNew.setForeground(new java.awt.Color(255, 255, 255));

        lblConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfirm.setForeground(new java.awt.Color(148, 163, 184));
        lblConfirm.setText("Confirm New Password");

        pfConfirm.setBackground(new java.awt.Color(12, 16, 28));
        pfConfirm.setText("jPasswordField1");

        btnChange.setBackground(new java.awt.Color(99, 102, 241));
        btnChange.setForeground(new java.awt.Color(255, 255, 255));
        btnChange.setText("Update Password");
        btnChange.setBorderPainted(false);
        btnChange.setFocusPainted(false);
        btnChange.addActionListener(this::btnChangeActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(lblNew)
                            .addComponent(lblCurrent)
                            .addComponent(btnChange)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pfConfirm, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pfNew, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pfCurrent, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblConfirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblStatus)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(24, 24, 24)
                .addComponent(lblCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNew)
                .addGap(18, 18, 18)
                .addComponent(pfNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfirm)
                .addGap(18, 18, 18)
                .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChange)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
         String current = new String(pfCurrent.getPassword());
    String newPass = new String(pfNew.getPassword()).trim();
    String confirm = new String(pfConfirm.getPassword()).trim();

    if (newPass.isEmpty()) {
        setStatus("New password cannot be empty.", false); return;
    }
    if (newPass.length() < 6) {
        setStatus("Password must be at least 6 characters.", false); return;
    }
    if (!newPass.equals(confirm)) {
        setStatus("New passwords do not match.", false); return;
    }

   esports.controller.ManagerController ctrl =
    new esports.controller.ManagerController();
String err = ctrl.changeOwnPassword(current, newPass);

    if (err == null) {
        setStatus("Password changed successfully!", true);
        pfCurrent.setText("");
        pfNew.setText("");
        pfConfirm.setText("");
    } else {
        setStatus(err, false);
    }
    }//GEN-LAST:event_btnChangeActionPerformed
private void setStatus(String msg, boolean success) {
    lblStatus.setText(msg);
    lblStatus.setForeground(success
        ? new java.awt.Color(16, 185, 129)
        : new java.awt.Color(239, 68, 68));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField pfConfirm;
    private javax.swing.JPasswordField pfCurrent;
    private javax.swing.JPasswordField pfNew;
    // End of variables declaration//GEN-END:variables
}
